
package it.lutech.c2sense.pee.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PeeWSImplService", targetNamespace = "http://ws.pee.c2sense.lutech.it/", wsdlLocation = "http://localhost:8080/pee/ws/PeeWS?wsdl")
public class PeeWSImplProxy
    extends Service
{

    private final static URL PeeWSIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/pee/ws/PeeWS?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PeeWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public PeeWSImplProxy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PeeWSImplProxy() {
        super(PeeWSIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.pee.c2sense.lutech.it/", "PeeWSImplService"));
    }

    /**
     * 
     * @return
     *     returns PeeWSProxy
     */
    @WebEndpoint(name = "PeeWSImplPort")
    public PeeWSProxy getPeeWSImplPort() {
        return super.getPort(new QName("http://ws.pee.c2sense.lutech.it/", "PeeWSImplPort"), PeeWSProxy.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PeeWSProxy
     */
    @WebEndpoint(name = "PeeWSImplPort")
    public PeeWSProxy getPeeWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.pee.c2sense.lutech.it/", "PeeWSImplPort"), PeeWSProxy.class, features);
    }

}
